export const items = [
    { id: 1, name: "Apple  1KG", price: 150, imgPath: require('./assets/images/apple.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/waterproof-jacket.jpg') }, { id: 2, imgPath: require('./assets/images/waterproof-jacket-2.jpg') } ], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 50, rating: 4.5, category: 'male' },
    { id: 2, name: "Banana 12pcs", price: 35, imgPath: require('./assets/images/banana.jpeg'), gallery: [{ id: 1, imgPath: require('./assets/images/black-military-shirt.jpg') }, { id: 2, imgPath: require('./assets/images/black-military-shirt-2.jpg') }, { id: 3, imgPath: require('./assets/images/black-military-shirt-3.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 3, name: "Dragan fruit 1pc", price: 50, imgPath: require('./assets/images/dragon.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/womens-formal-dress.jpg')}, { id: 2, imgPath: require('./assets/images/womens-formal-dress-2.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 32, rating: 4.9, category: 'female' },
    { id: 4, name: "orange 1kg", price: 59, imgPath: require('./assets/images/orange.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/mens-jacket-autumn.jpg') }, { id: 2, imgPath: require('./assets/images/mens-jacket-autumn-2.jpg')} ], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 23, rating: 5, category: 'male' },
    { id: 5, name: "Tomato 1kg", price: 35, imgPath: require('./assets/images/tomato.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/summer-dresses-one-shoulderr-ruffles.jpg') }, { id: 2, imgPath: require('./assets/images/summer-dresses-one-shoulderr-ruffles-2.jpg')}], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 15, rating: 5, category: 'female' },
    { id: 6, name: "Mango 1kg", price: 30, imgPath: require('./assets/images/mango.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/casual-mens-jacket.jpg')}, { id: 2, imgPath: require('./assets/images/casual-mens-jacket-2.jpg')}], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 50, rating: 4, category: 'male', category: 'male' },
    { id: 7, name: "Eggs 12pcs", price: 65, imgPath: require('./assets/images/eggs.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/size-cotton-bed-sheet.jpg') }, { id: 2, imgPath: require('./assets/images/size-cotton-bed-sheet-2.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.2, category: 'home' },
    { id: 8, name: "COW Ghee 1kg", price: 699, imgPath: require('./assets/images/ghee.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/sleeved_shirt.jpg')}, { id: 2, imgPath: require('./assets/images/sleeved-shirt-2.jpg')}], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 48, rating: 5, category: 'male' },
    { id: 9, name: "Paneer 250gms", price: 90, imgPath: require('./assets/images/paneer.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/Sheath-O-Neck-Mini-Dress-Casual-Coat-Two-Pieces.jpg') }, { id: 2, imgPath: require('./assets/images/Sheath-O-Neck-Mini-Dress-Casual-Coat-Two-Pieces-2.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 15, rating: 4.9, category: 'female' },
    { id: 10, name: "Milk 1ltr", price: 60, imgPath: require('./assets/images/milk.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/Women-Dresses-With-Pocket-Solid-Color-Long-Sleeve.jpg') }, { id: 2, imgPath: require('./assets/images/Women-Dresses-With-Pocket-Solid-Color-Long-Sleeve-2.jpg') } ], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 25, rating: 4.3, category: 'female' },
    // { id: 11, name: "Global Village BedSheet", price: 20, imgPath: require('./assets/images/global-village-bed-sheet.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/global-village-bed-sheet.jpg') }, { id: 2, imgPath: require('./assets/images/global-village-bed-sheet-2.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 52, rating: 3.9, category: 'home' },
    // { id: 12, name: "Kids Toddler Cloth", price: 10, imgPath: require('./assets/images/kids-toddler-cloth.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/kids-toddler-cloth.jpg') }, { id: 2, imgPath: require('./assets/images/kids-toddler-cloth-2.jpg')}], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 250, rating: 4.8, category: 'kid' },
    // { id: 13, name: "Men Formal Business Vest Jacket", price: 24, imgPath: require('./assets/images/Men-Formal-Business-Vest-Jacket.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/Men-Formal-Business-Vest-Jacket.jpg') }, { id: 2, imgPath: require('./assets/images/Men-Formal-Business-Vest-Jacket-2.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 250, rating: 4.8, category: 'male' },
    // { id: 16, name: "Ellesse Hoodie", price: 30, imgPath: require('./assets/images/ellesse_hoodie.jpg'), gallery: [{ id: 1, imgPath: require('./assets/images/ellesse_hoodie.jpg') }, { id: 2, imgPath: require('./assets/images/ellesse-hoodie-2.jpg')}, { id: 3, imgPath: require('./assets/images/ellesse-hoodie-3.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 450, rating: 5, category: 'male' }
  ]